export type ConnectorStatus = 'live' | 'early_access' | 'coming_soon';

export interface ConnectorEntry {
  id: string;            // kebab-case, unique
  name: string;          // display name
  category: string;      // one of CONNECTOR_CATEGORIES below (exact string)
  status: ConnectorStatus;
  whatItDoes: string;    // one concise sentence, Nibbin voice
  domain: string | null; // brand root domain for Clearbit logo (logo.clearbit.com/{domain}); null if no brand/logo
}

export const CONNECTOR_CATEGORIES: string[] = [
  'Email',
  'Calendar & Scheduling',
  'Client Inbox & Support',
  'CRM & Client Management',
  'Payments & Invoicing',
  'Finance & Banking',
  'Forms, Contracts & E-sign',
  'Notes & Documents',
  'Storage & Files',
  'Photography & Creative Delivery',
  'Design & Portfolio',
  'Video & Motion',
  'Music & Audio',
  'Content Creation & Monetization',
  'Writing & Publishing',
  'Courses & Communities',
  'Social & Marketing',
  'Messaging & Meetings',
  'E-commerce & Sites',
  'Project & Productivity',
  'Time Tracking',
  'Developer & Technical',
  'Freelance Marketplaces',
  'Print & Fulfillment',
  'Automation',
  'Advanced',
];

export const CONNECTORS: ConnectorEntry[] = [

  // ── Email ──

  {
    id: 'gmail',
    name: 'Gmail',
    category: 'Email',
    status: 'live',
    whatItDoes: 'Surface unanswered enquiries and draft client replies in your voice.',
    domain: 'gmail.com',
  },
  {
    id: 'outlook-m365',
    name: 'Outlook / Microsoft 365',
    category: 'Email',
    status: 'early_access',
    whatItDoes: 'Watch your Outlook inbox for client threads that need a reply and draft responses before you open them.',
    domain: 'microsoft.com',
  },
  {
    id: 'imap-smtp',
    name: 'IMAP / SMTP',
    category: 'Email',
    status: 'early_access',
    whatItDoes: 'Connect any email host via standard protocols so your nibbins can monitor and draft from your preferred inbox.',
    domain: null,
  },
  {
    id: 'icloud-mail',
    name: 'iCloud Mail',
    category: 'Email',
    status: 'coming_soon',
    whatItDoes: 'Monitor your iCloud inbox for enquiries from new leads and flag threads that have gone quiet for too long.',
    domain: 'icloud.com',
  },
  {
    id: 'fastmail',
    name: 'Fastmail',
    category: 'Email',
    status: 'coming_soon',
    whatItDoes: 'Track client conversations in Fastmail and draft follow-ups when a thread stalls past your response window.',
    domain: 'fastmail.com',
  },
  {
    id: 'proton-mail',
    name: 'Proton Mail',
    category: 'Email',
    status: 'coming_soon',
    whatItDoes: 'Surface unanswered enquiries in your Proton inbox and queue draft replies for your review.',
    domain: 'proton.me',
  },
  {
    id: 'yahoo-mail',
    name: 'Yahoo Mail',
    category: 'Email',
    status: 'coming_soon',
    whatItDoes: 'Watch your Yahoo inbox for client messages that need a timely reply and draft them before you forget.',
    domain: 'yahoo.com',
  },

  // ── Calendar & Scheduling ──

  {
    id: 'google-calendar',
    name: 'Google Calendar',
    category: 'Calendar & Scheduling',
    status: 'early_access',
    whatItDoes: 'Detect upcoming shoots or calls without confirmed prep items and nudge you to send a session brief.',
    domain: 'calendar.google.com',
  },
  {
    id: 'outlook-calendar',
    name: 'Outlook Calendar',
    category: 'Calendar & Scheduling',
    status: 'early_access',
    whatItDoes: 'Flag client meetings approaching without an agenda and draft a pre-call checklist for your review.',
    domain: 'microsoft.com',
  },
  {
    id: 'calendly',
    name: 'Calendly',
    category: 'Calendar & Scheduling',
    status: 'early_access',
    whatItDoes: 'Spot new Calendly bookings and draft a confirmation email with your session prep instructions.',
    domain: 'calendly.com',
  },
  {
    id: 'cal-com',
    name: 'Cal.com',
    category: 'Calendar & Scheduling',
    status: 'early_access',
    whatItDoes: 'Detect new Cal.com bookings and queue a personalised onboarding message for each new client.',
    domain: 'cal.com',
  },
  {
    id: 'caldav',
    name: 'CalDAV',
    category: 'Calendar & Scheduling',
    status: 'early_access',
    whatItDoes: 'Connect any CalDAV-compatible calendar so your nibbins can track deadlines and flag unconfirmed bookings.',
    domain: null,
  },
  {
    id: 'acuity-scheduling',
    name: 'Acuity Scheduling',
    category: 'Calendar & Scheduling',
    status: 'coming_soon',
    whatItDoes: 'Watch for new Acuity appointments and draft intake forms or prep emails tailored to each booking type.',
    domain: 'acuityscheduling.com',
  },
  {
    id: 'savvycal',
    name: 'SavvyCal',
    category: 'Calendar & Scheduling',
    status: 'coming_soon',
    whatItDoes: 'Detect new SavvyCal bookings and prompt you to send a welcome message before the meeting.',
    domain: 'savvycal.com',
  },

  // ── Client Inbox & Support ──

  {
    id: 'front',
    name: 'Front',
    category: 'Client Inbox & Support',
    status: 'coming_soon',
    whatItDoes: 'Flag shared inbox conversations that have gone unanswered and draft a reply for the assigned teammate.',
    domain: 'front.com',
  },
  {
    id: 'help-scout',
    name: 'Help Scout',
    category: 'Client Inbox & Support',
    status: 'coming_soon',
    whatItDoes: 'Surface open client support conversations overdue for a reply and draft a resolution message for your approval.',
    domain: 'helpscout.com',
  },
  {
    id: 'missive',
    name: 'Missive',
    category: 'Client Inbox & Support',
    status: 'coming_soon',
    whatItDoes: 'Monitor shared Missive threads and nudge collaborators when a client conversation needs picking up.',
    domain: 'missiveapp.com',
  },
  {
    id: 'intercom',
    name: 'Intercom',
    category: 'Client Inbox & Support',
    status: 'coming_soon',
    whatItDoes: 'Detect unassigned or long-open Intercom conversations and draft a suggested reply in your brand voice.',
    domain: 'intercom.com',
  },
  {
    id: 'zendesk',
    name: 'Zendesk',
    category: 'Client Inbox & Support',
    status: 'coming_soon',
    whatItDoes: 'Flag tickets that have missed their SLA and queue a holding reply while you prepare the full answer.',
    domain: 'zendesk.com',
  },

  // ── CRM & Client Management ──

  {
    id: 'honeybook',
    name: 'HoneyBook',
    category: 'CRM & Client Management',
    status: 'early_access',
    whatItDoes: 'Flag overdue invoices and prompt you to chase late-paying clients.',
    domain: 'honeybook.com',
  },
  {
    id: 'notion',
    name: 'Notion',
    category: 'CRM & Client Management',
    status: 'early_access',
    whatItDoes: 'Watch your Notion project databases for stalled client tasks and draft a status update for their approval.',
    domain: 'notion.so',
  },
  {
    id: 'dubsado',
    name: 'Dubsado',
    category: 'CRM & Client Management',
    status: 'coming_soon',
    whatItDoes: 'Surface leads stuck in a workflow stage and draft a personalised nudge to move them forward.',
    domain: 'dubsado.com',
  },
  {
    id: '17hats',
    name: '17hats',
    category: 'CRM & Client Management',
    status: 'coming_soon',
    whatItDoes: 'Flag unsigned contracts or unpaid quotes in 17hats and draft a polite follow-up to the client.',
    domain: '17hats.com',
  },
  {
    id: 'airtable',
    name: 'Airtable',
    category: 'CRM & Client Management',
    status: 'coming_soon',
    whatItDoes: 'Watch your Airtable client base for records with overdue dates and draft a check-in message for each.',
    domain: 'airtable.com',
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    category: 'CRM & Client Management',
    status: 'coming_soon',
    whatItDoes: 'Spot deals that have gone cold in HubSpot and draft a re-engagement email before the lead moves on.',
    domain: 'hubspot.com',
  },
  {
    id: 'pipedrive',
    name: 'Pipedrive',
    category: 'CRM & Client Management',
    status: 'coming_soon',
    whatItDoes: 'Flag deals stalled in a pipeline stage and draft a follow-up activity for you to approve and send.',
    domain: 'pipedrive.com',
  },
  {
    id: 'copper',
    name: 'Copper',
    category: 'CRM & Client Management',
    status: 'coming_soon',
    whatItDoes: 'Detect contacts without a recent touch in Copper and queue a personalised catch-up message.',
    domain: 'copper.com',
  },
  {
    id: 'zoho-crm',
    name: 'Zoho CRM',
    category: 'CRM & Client Management',
    status: 'coming_soon',
    whatItDoes: 'Surface leads and deals past their expected close date and draft a timely follow-up for your review.',
    domain: 'zoho.com',
  },

  // ── Payments & Invoicing ──

  {
    id: 'stripe',
    name: 'Stripe',
    category: 'Payments & Invoicing',
    status: 'early_access',
    whatItDoes: 'Flag overdue invoices and prompt you to chase late-paying clients.',
    domain: 'stripe.com',
  },
  {
    id: 'square',
    name: 'Square',
    category: 'Payments & Invoicing',
    status: 'early_access',
    whatItDoes: 'Surface unpaid Square invoices and draft a polite payment reminder in your voice.',
    domain: 'squareup.com',
  },
  {
    id: 'paypal',
    name: 'PayPal',
    category: 'Payments & Invoicing',
    status: 'early_access',
    whatItDoes: 'Detect overdue PayPal invoices and draft a follow-up reminder to send the client.',
    domain: 'paypal.com',
  },
  {
    id: 'quickbooks',
    name: 'QuickBooks',
    category: 'Payments & Invoicing',
    status: 'early_access',
    whatItDoes: 'Flag outstanding QuickBooks invoices past due and prompt you to chase before they age further.',
    domain: 'quickbooks.intuit.com',
  },
  {
    id: 'xero',
    name: 'Xero',
    category: 'Payments & Invoicing',
    status: 'coming_soon',
    whatItDoes: 'Surface overdue Xero invoices and draft a payment chase in your tone before you need to ask.',
    domain: 'xero.com',
  },
  {
    id: 'freshbooks',
    name: 'FreshBooks',
    category: 'Payments & Invoicing',
    status: 'coming_soon',
    whatItDoes: 'Flag unpaid FreshBooks invoices and prepare a reminder email you can send with one click.',
    domain: 'freshbooks.com',
  },
  {
    id: 'wave',
    name: 'Wave',
    category: 'Payments & Invoicing',
    status: 'coming_soon',
    whatItDoes: 'Detect invoices that have gone past due in Wave and draft a polite follow-up for your review.',
    domain: 'waveapps.com',
  },
  {
    id: 'bonsai',
    name: 'Bonsai',
    category: 'Payments & Invoicing',
    status: 'coming_soon',
    whatItDoes: 'Watch Bonsai for unsigned contracts and unpaid invoices and queue a nudge to the client.',
    domain: 'hellobonsai.com',
  },
  {
    id: 'bill-com',
    name: 'Bill.com',
    category: 'Payments & Invoicing',
    status: 'coming_soon',
    whatItDoes: 'Flag bills and invoices in Bill.com that are approaching or past due and prompt the right action.',
    domain: 'bill.com',
  },

  // ── Finance & Banking ──

  {
    id: 'mercury',
    name: 'Mercury',
    category: 'Finance & Banking',
    status: 'coming_soon',
    whatItDoes: 'Watch your Mercury account for large or unusual transactions and flag them before your next bookkeeping session.',
    domain: 'mercury.com',
  },
  {
    id: 'found',
    name: 'Found',
    category: 'Finance & Banking',
    status: 'coming_soon',
    whatItDoes: 'Track business expenses in Found and remind you to categorise uncoded transactions before tax season.',
    domain: 'found.com',
  },
  {
    id: 'lili',
    name: 'Lili',
    category: 'Finance & Banking',
    status: 'coming_soon',
    whatItDoes: 'Monitor your Lili balance and flag months where income dips below your personal floor so you can act early.',
    domain: 'lili.co',
  },
  {
    id: 'relay',
    name: 'Relay',
    category: 'Finance & Banking',
    status: 'coming_soon',
    whatItDoes: 'Surface uncategorised Relay transactions and draft a short bookkeeping summary for your records.',
    domain: 'relayfi.com',
  },
  {
    id: 'novo',
    name: 'Novo',
    category: 'Finance & Banking',
    status: 'coming_soon',
    whatItDoes: 'Flag unreconciled expenses in Novo and prompt you to attach receipts before they become a tax headache.',
    domain: 'novo.co',
  },
  {
    id: 'expensify',
    name: 'Expensify',
    category: 'Finance & Banking',
    status: 'coming_soon',
    whatItDoes: 'Detect unsubmitted expense reports in Expensify and remind you to send them for reimbursement.',
    domain: 'expensify.com',
  },
  {
    id: 'ramp',
    name: 'Ramp',
    category: 'Finance & Banking',
    status: 'coming_soon',
    whatItDoes: 'Flag Ramp card transactions missing receipts or memo notes before your monthly close.',
    domain: 'ramp.com',
  },
  {
    id: 'brex',
    name: 'Brex',
    category: 'Finance & Banking',
    status: 'coming_soon',
    whatItDoes: 'Surface unreceipted Brex spend and prompt you to add context before your accountant asks.',
    domain: 'brex.com',
  },
  {
    id: 'gusto',
    name: 'Gusto',
    category: 'Finance & Banking',
    status: 'coming_soon',
    whatItDoes: 'Alert you when a Gusto payroll run is approaching and confirm your contractor hours are up to date.',
    domain: 'gusto.com',
  },

  // ── Forms, Contracts & E-sign ──

  {
    id: 'typeform',
    name: 'Typeform',
    category: 'Forms, Contracts & E-sign',
    status: 'coming_soon',
    whatItDoes: 'Watch for new Typeform enquiry responses and draft a personalised reply to each lead within minutes.',
    domain: 'typeform.com',
  },
  {
    id: 'jotform',
    name: 'Jotform',
    category: 'Forms, Contracts & E-sign',
    status: 'coming_soon',
    whatItDoes: 'Surface new Jotform submissions from prospective clients and queue a follow-up message for your approval.',
    domain: 'jotform.com',
  },
  {
    id: 'google-forms',
    name: 'Google Forms',
    category: 'Forms, Contracts & E-sign',
    status: 'coming_soon',
    whatItDoes: 'Detect new Google Form responses from clients or leads and draft an appropriate reply in your voice.',
    domain: 'docs.google.com',
  },
  {
    id: 'docusign',
    name: 'DocuSign',
    category: 'Forms, Contracts & E-sign',
    status: 'coming_soon',
    whatItDoes: 'Flag envelopes that have been sent but not signed and draft a polite reminder to the outstanding signer.',
    domain: 'docusign.com',
  },
  {
    id: 'dropbox-sign',
    name: 'Dropbox Sign',
    category: 'Forms, Contracts & E-sign',
    status: 'coming_soon',
    whatItDoes: 'Surface signature requests left unsigned for more than a day and queue a gentle follow-up for you to send.',
    domain: 'hellosign.com',
  },
  {
    id: 'pandadoc',
    name: 'PandaDoc',
    category: 'Forms, Contracts & E-sign',
    status: 'coming_soon',
    whatItDoes: 'Alert you when a PandaDoc proposal has been viewed but not signed so you can follow up at the right moment.',
    domain: 'pandadoc.com',
  },
  {
    id: 'adobe-acrobat-sign',
    name: 'Adobe Acrobat Sign',
    category: 'Forms, Contracts & E-sign',
    status: 'coming_soon',
    whatItDoes: 'Flag agreements sent for signature that remain unsigned and draft a timely reminder for each signer.',
    domain: 'acrobat.adobe.com',
  },
  {
    id: 'signnow',
    name: 'SignNow',
    category: 'Forms, Contracts & E-sign',
    status: 'coming_soon',
    whatItDoes: 'Detect documents pending signature in SignNow and prepare a follow-up nudge before deadlines slip.',
    domain: 'signnow.com',
  },
  {
    id: 'concord',
    name: 'Concord',
    category: 'Forms, Contracts & E-sign',
    status: 'coming_soon',
    whatItDoes: 'Surface contracts stuck in review and flag renewal dates approaching so nothing auto-renews unnoticed.',
    domain: 'concord.app',
  },

  // ── Notes & Documents ──

  {
    id: 'evernote',
    name: 'Evernote',
    category: 'Notes & Documents',
    status: 'coming_soon',
    whatItDoes: 'Scan your Evernote notebooks for action items buried in meeting notes and surface them as a to-do list.',
    domain: 'evernote.com',
  },
  {
    id: 'onenote',
    name: 'OneNote',
    category: 'Notes & Documents',
    status: 'coming_soon',
    whatItDoes: 'Find client-related notes in OneNote that contain open commitments and remind you to follow through.',
    domain: 'onenote.com',
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    category: 'Notes & Documents',
    status: 'coming_soon',
    whatItDoes: 'Detect notes tagged as client tasks in your Obsidian vault and flag ones that have gone untouched too long.',
    domain: 'obsidian.md',
  },
  {
    id: 'coda',
    name: 'Coda',
    category: 'Notes & Documents',
    status: 'coming_soon',
    whatItDoes: 'Watch Coda docs for table rows with overdue dates and draft a status update or reminder for the right person.',
    domain: 'coda.io',
  },
  {
    id: 'confluence',
    name: 'Confluence',
    category: 'Notes & Documents',
    status: 'coming_soon',
    whatItDoes: 'Surface stale Confluence pages that reference upcoming deadlines and nudge you to update them.',
    domain: 'atlassian.com',
  },
  {
    id: 'dropbox-paper',
    name: 'Dropbox Paper',
    category: 'Notes & Documents',
    status: 'coming_soon',
    whatItDoes: 'Find shared Paper docs with unresolved comments and prompt you to close them before the next client review.',
    domain: 'dropbox.com',
  },
  {
    id: 'google-keep',
    name: 'Google Keep',
    category: 'Notes & Documents',
    status: 'coming_soon',
    whatItDoes: 'Surface Keep notes labelled as client reminders and nudge you when their associated dates are near.',
    domain: 'keep.google.com',
  },

  // ── Storage & Files ──

  {
    id: 'google-drive',
    name: 'Google Drive',
    category: 'Storage & Files',
    status: 'early_access',
    whatItDoes: 'Flag galleries or files that were shared with a client but never opened, and prompt you to follow up.',
    domain: 'drive.google.com',
  },
  {
    id: 'google-sheets-docs',
    name: 'Google Sheets / Docs',
    category: 'Storage & Files',
    status: 'early_access',
    whatItDoes: 'Detect sheets or docs shared with clients that contain unresolved comments and surface them for action.',
    domain: 'docs.google.com',
  },
  {
    id: 'dropbox',
    name: 'Dropbox',
    category: 'Storage & Files',
    status: 'coming_soon',
    whatItDoes: 'Flag Dropbox folders shared with clients that show no activity and prompt you to check in.',
    domain: 'dropbox.com',
  },
  {
    id: 'onedrive',
    name: 'OneDrive',
    category: 'Storage & Files',
    status: 'coming_soon',
    whatItDoes: 'Detect OneDrive files shared with clients that were viewed but not downloaded and prompt a follow-up.',
    domain: 'onedrive.live.com',
  },
  {
    id: 'box',
    name: 'Box',
    category: 'Storage & Files',
    status: 'coming_soon',
    whatItDoes: 'Surface Box folders delivered to clients with no download activity and nudge you to check in.',
    domain: 'box.com',
  },

  // ── Photography & Creative Delivery ──

  {
    id: 'pixieset',
    name: 'Pixieset',
    category: 'Photography & Creative Delivery',
    status: 'early_access',
    whatItDoes: 'Flag galleries that were delivered but never downloaded by the client.',
    domain: 'pixieset.com',
  },
  {
    id: 'shootproof',
    name: 'ShootProof',
    category: 'Photography & Creative Delivery',
    status: 'coming_soon',
    whatItDoes: 'Detect galleries delivered in ShootProof that have not been opened and draft a gentle reminder to the client.',
    domain: 'shootproof.com',
  },
  {
    id: 'pic-time',
    name: 'Pic-Time',
    category: 'Photography & Creative Delivery',
    status: 'coming_soon',
    whatItDoes: 'Flag Pic-Time galleries that are live but have no client activity and prompt a follow-up before the link expires.',
    domain: 'pic-time.com',
  },
  {
    id: 'cloudspot',
    name: 'CloudSpot',
    category: 'Photography & Creative Delivery',
    status: 'coming_soon',
    whatItDoes: 'Surface CloudSpot galleries with zero client views and queue a delivery reminder in your voice.',
    domain: 'cloudspot.com',
  },
  {
    id: 'adobe-lightroom',
    name: 'Adobe Lightroom',
    category: 'Photography & Creative Delivery',
    status: 'coming_soon',
    whatItDoes: 'Detect Lightroom albums shared to clients that have not been accessed and remind you to follow up.',
    domain: 'lightroom.adobe.com',
  },
  {
    id: 'tave',
    name: 'Táve',
    category: 'Photography & Creative Delivery',
    status: 'coming_soon',
    whatItDoes: 'Flag open leads and unsigned contracts in Táve and draft a follow-up before the booking window closes.',
    domain: 'tave.com',
  },
  {
    id: 'studio-ninja',
    name: 'Studio Ninja',
    category: 'Photography & Creative Delivery',
    status: 'coming_soon',
    whatItDoes: 'Surface Studio Ninja leads that stalled mid-workflow and draft a re-engagement email for each.',
    domain: 'studioninja.com',
  },
  {
    id: 'iris-works',
    name: 'Iris Works',
    category: 'Photography & Creative Delivery',
    status: 'coming_soon',
    whatItDoes: 'Detect unsigned Iris Works contracts and outstanding invoices and queue a polite nudge to the client.',
    domain: 'iris-works.com',
  },
  {
    id: 'sprout-studio',
    name: 'Sprout Studio',
    category: 'Photography & Creative Delivery',
    status: 'coming_soon',
    whatItDoes: 'Flag Sprout Studio bookings with overdue payments or unsigned agreements before the session date.',
    domain: 'sproutstudio.io',
  },
  {
    id: 'zenfolio',
    name: 'Zenfolio',
    category: 'Photography & Creative Delivery',
    status: 'coming_soon',
    whatItDoes: 'Flag Zenfolio galleries with no client downloads and prompt you to send a personalised delivery nudge.',
    domain: 'zenfolio.com',
  },
  {
    id: 'smugmug',
    name: 'SmugMug',
    category: 'Photography & Creative Delivery',
    status: 'coming_soon',
    whatItDoes: 'Surface SmugMug galleries shared with clients that show no recent activity and queue a check-in message.',
    domain: 'smugmug.com',
  },
  {
    id: 'format',
    name: 'Format',
    category: 'Photography & Creative Delivery',
    status: 'coming_soon',
    whatItDoes: 'Detect client proofing galleries on Format with no approved selections and draft a reminder to move things along.',
    domain: 'format.com',
  },
  {
    id: 'adobe-portfolio',
    name: 'Adobe Portfolio',
    category: 'Photography & Creative Delivery',
    status: 'coming_soon',
    whatItDoes: 'Flag portfolio projects shared for client review that have received no feedback and nudge the recipient.',
    domain: 'portfolio.adobe.com',
  },

  // ── Design & Portfolio ──

  {
    id: 'figma',
    name: 'Figma',
    category: 'Design & Portfolio',
    status: 'coming_soon',
    whatItDoes: 'Detect Figma files shared for client review that have unresolved comments and surface them for your reply.',
    domain: 'figma.com',
  },
  {
    id: 'behance',
    name: 'Behance',
    category: 'Design & Portfolio',
    status: 'coming_soon',
    whatItDoes: 'Surface new Behance project comments and inquiries from potential clients before they go unanswered.',
    domain: 'behance.net',
  },
  {
    id: 'dribbble',
    name: 'Dribbble',
    category: 'Design & Portfolio',
    status: 'coming_soon',
    whatItDoes: 'Flag new Dribbble messages from potential clients and draft a professional reply to each enquiry.',
    domain: 'dribbble.com',
  },
  {
    id: 'canva',
    name: 'Canva',
    category: 'Design & Portfolio',
    status: 'coming_soon',
    whatItDoes: 'Detect Canva designs shared with clients for approval that have not been reviewed and prompt a follow-up.',
    domain: 'canva.com',
  },
  {
    id: 'adobe-creative-cloud',
    name: 'Adobe Creative Cloud',
    category: 'Design & Portfolio',
    status: 'coming_soon',
    whatItDoes: 'Surface Creative Cloud shared assets with pending client feedback and remind you to nudge them along.',
    domain: 'adobe.com',
  },
  {
    id: 'webflow',
    name: 'Webflow',
    category: 'Design & Portfolio',
    status: 'coming_soon',
    whatItDoes: 'Flag Webflow projects in staging that have been shared for client sign-off but have received no approval.',
    domain: 'webflow.com',
  },
  {
    id: 'framer',
    name: 'Framer',
    category: 'Design & Portfolio',
    status: 'coming_soon',
    whatItDoes: 'Detect Framer prototypes shared with clients that have unreviewed comments and draft a discussion summary.',
    domain: 'framer.com',
  },
  {
    id: 'invision',
    name: 'InVision',
    category: 'Design & Portfolio',
    status: 'coming_soon',
    whatItDoes: 'Surface InVision prototypes awaiting client feedback and prompt you to follow up before iteration stalls.',
    domain: 'invisionapp.com',
  },
  {
    id: '99designs',
    name: '99designs',
    category: 'Design & Portfolio',
    status: 'coming_soon',
    whatItDoes: 'Flag active design contests or projects with pending client feedback and prompt you to keep the momentum going.',
    domain: '99designs.com',
  },

  // ── Video & Motion ──

  {
    id: 'frame-io',
    name: 'Frame.io',
    category: 'Video & Motion',
    status: 'coming_soon',
    whatItDoes: 'Surface Frame.io review links shared with clients that have unresolved comments or no approval status.',
    domain: 'frame.io',
  },
  {
    id: 'vimeo',
    name: 'Vimeo',
    category: 'Video & Motion',
    status: 'coming_soon',
    whatItDoes: 'Flag Vimeo videos shared privately for client review that show no views and prompt a delivery follow-up.',
    domain: 'vimeo.com',
  },
  {
    id: 'wistia',
    name: 'Wistia',
    category: 'Video & Motion',
    status: 'coming_soon',
    whatItDoes: 'Detect Wistia videos delivered to clients with low engagement and suggest a follow-up to confirm satisfaction.',
    domain: 'wistia.com',
  },
  {
    id: 'wipster',
    name: 'Wipster',
    category: 'Video & Motion',
    status: 'coming_soon',
    whatItDoes: 'Surface Wipster video reviews with pending client feedback and draft a nudge to collect their approvals.',
    domain: 'wipster.io',
  },
  {
    id: 'descript',
    name: 'Descript',
    category: 'Video & Motion',
    status: 'coming_soon',
    whatItDoes: 'Flag Descript projects shared for client review that have open comments or no final approval.',
    domain: 'descript.com',
  },
  {
    id: 'riverside-fm',
    name: 'Riverside.fm',
    category: 'Video & Motion',
    status: 'coming_soon',
    whatItDoes: 'Alert you when a Riverside recording is ready to deliver and draft the client handoff message.',
    domain: 'riverside.fm',
  },
  {
    id: 'loom',
    name: 'Loom',
    category: 'Video & Motion',
    status: 'coming_soon',
    whatItDoes: 'Detect Loom videos sent to clients that have not been viewed and queue a reminder to watch the update.',
    domain: 'loom.com',
  },
  {
    id: 'veed',
    name: 'VEED',
    category: 'Video & Motion',
    status: 'coming_soon',
    whatItDoes: 'Flag VEED projects shared for feedback that have received no response and draft a follow-up to the client.',
    domain: 'veed.io',
  },

  // ── Music & Audio ──

  {
    id: 'soundcloud',
    name: 'SoundCloud',
    category: 'Music & Audio',
    status: 'coming_soon',
    whatItDoes: 'Surface new SoundCloud comments or messages from fans and collaborators before they go unacknowledged.',
    domain: 'soundcloud.com',
  },
  {
    id: 'bandcamp',
    name: 'Bandcamp',
    category: 'Music & Audio',
    status: 'coming_soon',
    whatItDoes: 'Flag new Bandcamp sales or fan messages and draft a personal thank-you to build the relationship.',
    domain: 'bandcamp.com',
  },
  {
    id: 'distrokid',
    name: 'DistroKid',
    category: 'Music & Audio',
    status: 'coming_soon',
    whatItDoes: 'Alert you when new royalty statements or distribution updates arrive in DistroKid so nothing gets missed.',
    domain: 'distrokid.com',
  },
  {
    id: 'tunecore',
    name: 'TuneCore',
    category: 'Music & Audio',
    status: 'coming_soon',
    whatItDoes: 'Surface TuneCore royalty reports when they land and flag earnings that look lower than your expected rate.',
    domain: 'tunecore.com',
  },
  {
    id: 'cd-baby',
    name: 'CD Baby',
    category: 'Music & Audio',
    status: 'coming_soon',
    whatItDoes: 'Detect new CD Baby statements and alert you when earnings clear so you can plan your next release budget.',
    domain: 'cdbaby.com',
  },
  {
    id: 'spotify-for-artists',
    name: 'Spotify for Artists',
    category: 'Music & Audio',
    status: 'coming_soon',
    whatItDoes: 'Flag unusual dips or spikes in Spotify streams and surface listener milestones worth sharing with your audience.',
    domain: 'artists.spotify.com',
  },
  {
    id: 'apple-music-for-artists',
    name: 'Apple Music for Artists',
    category: 'Music & Audio',
    status: 'coming_soon',
    whatItDoes: 'Surface Apple Music play milestones and new market trends in your listenership so you can act on momentum.',
    domain: 'artists.apple.com',
  },
  {
    id: 'disco',
    name: 'Disco',
    category: 'Music & Audio',
    status: 'coming_soon',
    whatItDoes: 'Detect new Disco pitch submissions and surface playback activity so you know when A&Rs are listening.',
    domain: 'disco.ac',
  },

  // ── Content Creation & Monetization ──

  {
    id: 'patreon',
    name: 'Patreon',
    category: 'Content Creation & Monetization',
    status: 'coming_soon',
    whatItDoes: 'Flag new Patreon messages from patrons and draft a reply before they feel ignored.',
    domain: 'patreon.com',
  },
  {
    id: 'substack',
    name: 'Substack',
    category: 'Content Creation & Monetization',
    status: 'coming_soon',
    whatItDoes: 'Surface new Substack subscriber replies and comments and draft responses to keep your community engaged.',
    domain: 'substack.com',
  },
  {
    id: 'ko-fi',
    name: 'Ko-fi',
    category: 'Content Creation & Monetization',
    status: 'coming_soon',
    whatItDoes: 'Flag new Ko-fi supporters and commission requests and draft a personalised thank-you for each.',
    domain: 'ko-fi.com',
  },
  {
    id: 'buy-me-a-coffee',
    name: 'Buy Me a Coffee',
    category: 'Content Creation & Monetization',
    status: 'coming_soon',
    whatItDoes: 'Surface new Buy Me a Coffee support messages and draft a warm acknowledgement for each supporter.',
    domain: 'buymeacoffee.com',
  },
  {
    id: 'gumroad',
    name: 'Gumroad',
    category: 'Content Creation & Monetization',
    status: 'coming_soon',
    whatItDoes: 'Flag new Gumroad customer messages or refund requests and draft a reply before the window to respond closes.',
    domain: 'gumroad.com',
  },
  {
    id: 'beehiiv',
    name: 'Beehiiv',
    category: 'Content Creation & Monetization',
    status: 'coming_soon',
    whatItDoes: 'Surface Beehiiv subscriber replies and draft responses to nurture your newsletter community.',
    domain: 'beehiiv.com',
  },
  {
    id: 'twitch',
    name: 'Twitch',
    category: 'Content Creation & Monetization',
    status: 'coming_soon',
    whatItDoes: 'Flag new Twitch subscriber messages and gifted sub milestones so you can acknowledge them off-stream.',
    domain: 'twitch.tv',
  },
  {
    id: 'podia',
    name: 'Podia',
    category: 'Content Creation & Monetization',
    status: 'coming_soon',
    whatItDoes: 'Surface new Podia customer messages and draft replies so no buyer feels unsupported after purchase.',
    domain: 'podia.com',
  },

  // ── Writing & Publishing ──

  {
    id: 'medium',
    name: 'Medium',
    category: 'Writing & Publishing',
    status: 'coming_soon',
    whatItDoes: 'Surface new Medium reader responses to your articles and draft replies to keep the conversation going.',
    domain: 'medium.com',
  },
  {
    id: 'ghost',
    name: 'Ghost',
    category: 'Writing & Publishing',
    status: 'coming_soon',
    whatItDoes: 'Flag Ghost member messages and new subscriber replies so your newsletter community never goes unheard.',
    domain: 'ghost.org',
  },

  // ── Courses & Communities ──

  {
    id: 'teachable',
    name: 'Teachable',
    category: 'Courses & Communities',
    status: 'coming_soon',
    whatItDoes: 'Flag Teachable student messages and course completion milestones so you can send timely encouragement.',
    domain: 'teachable.com',
  },
  {
    id: 'thinkific',
    name: 'Thinkific',
    category: 'Courses & Communities',
    status: 'coming_soon',
    whatItDoes: 'Surface Thinkific student questions and stalled progress and draft a check-in to keep learners on track.',
    domain: 'thinkific.com',
  },
  {
    id: 'kajabi',
    name: 'Kajabi',
    category: 'Courses & Communities',
    status: 'coming_soon',
    whatItDoes: 'Detect new Kajabi member messages and draft replies to support your community without leaving the platform.',
    domain: 'kajabi.com',
  },
  {
    id: 'circle',
    name: 'Circle',
    category: 'Courses & Communities',
    status: 'coming_soon',
    whatItDoes: 'Surface new Circle community posts and DMs that need a host response before engagement drops.',
    domain: 'circle.so',
  },
  {
    id: 'mighty-networks',
    name: 'Mighty Networks',
    category: 'Courses & Communities',
    status: 'coming_soon',
    whatItDoes: 'Flag new Mighty Networks member activity and draft replies to keep your community feeling supported.',
    domain: 'mightynetworks.com',
  },
  {
    id: 'skool',
    name: 'Skool',
    category: 'Courses & Communities',
    status: 'coming_soon',
    whatItDoes: 'Detect new Skool community posts and student questions and draft a response to keep momentum high.',
    domain: 'skool.com',
  },
  {
    id: 'discord',
    name: 'Discord',
    category: 'Courses & Communities',
    status: 'coming_soon',
    whatItDoes: 'Flag DMs and unanswered threads in your Discord server and draft replies so members stay engaged.',
    domain: 'discord.com',
  },

  // ── Social & Marketing ──

  {
    id: 'instagram-dm',
    name: 'Instagram',
    category: 'Social & Marketing',
    status: 'early_access',
    whatItDoes: 'Surface unanswered Instagram DMs from potential clients and draft a reply before the lead goes cold.',
    domain: 'instagram.com',
  },
  {
    id: 'facebook',
    name: 'Facebook',
    category: 'Social & Marketing',
    status: 'coming_soon',
    whatItDoes: 'Flag unread Facebook Page messages from potential clients and draft a reply before they enquire elsewhere.',
    domain: 'facebook.com',
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    category: 'Social & Marketing',
    status: 'coming_soon',
    whatItDoes: 'Surface LinkedIn messages from leads and collaborators and draft professional replies in your voice.',
    domain: 'linkedin.com',
  },
  {
    id: 'x-twitter',
    name: 'X / Twitter',
    category: 'Social & Marketing',
    status: 'coming_soon',
    whatItDoes: 'Detect X DMs and client mentions that need a reply before they fall off your radar.',
    domain: 'x.com',
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    category: 'Social & Marketing',
    status: 'coming_soon',
    whatItDoes: 'Surface TikTok DMs from potential clients or collaborators and draft a timely reply in your tone.',
    domain: 'tiktok.com',
  },
  {
    id: 'pinterest',
    name: 'Pinterest',
    category: 'Social & Marketing',
    status: 'coming_soon',
    whatItDoes: 'Flag Pinterest messages from prospective clients and draft a reply to convert interest into a booking.',
    domain: 'pinterest.com',
  },
  {
    id: 'youtube',
    name: 'YouTube',
    category: 'Social & Marketing',
    status: 'coming_soon',
    whatItDoes: 'Surface YouTube comments and channel messages from potential clients and draft replies to build community.',
    domain: 'youtube.com',
  },
  {
    id: 'buffer',
    name: 'Buffer',
    category: 'Social & Marketing',
    status: 'coming_soon',
    whatItDoes: 'Alert you when your Buffer content queue is running low and prompt you to schedule the next batch of posts.',
    domain: 'buffer.com',
  },
  {
    id: 'later',
    name: 'Later',
    category: 'Social & Marketing',
    status: 'coming_soon',
    whatItDoes: 'Flag gaps in your Later content calendar and prompt you to fill them before your posting schedule runs dry.',
    domain: 'later.com',
  },
  {
    id: 'mailchimp',
    name: 'Mailchimp',
    category: 'Social & Marketing',
    status: 'coming_soon',
    whatItDoes: 'Surface Mailchimp campaigns with high unsubscribe rates and prompt you to review the content before the next send.',
    domain: 'mailchimp.com',
  },
  {
    id: 'kit-convertkit',
    name: 'Kit (ConvertKit)',
    category: 'Social & Marketing',
    status: 'coming_soon',
    whatItDoes: 'Flag Kit subscriber replies to your broadcasts and draft responses to nurture your email community.',
    domain: 'kit.com',
  },
  {
    id: 'flodesk',
    name: 'Flodesk',
    category: 'Social & Marketing',
    status: 'coming_soon',
    whatItDoes: 'Detect Flodesk email replies from new leads and draft a personalised follow-up to move them toward booking.',
    domain: 'flodesk.com',
  },
  {
    id: 'klaviyo',
    name: 'Klaviyo',
    category: 'Social & Marketing',
    status: 'coming_soon',
    whatItDoes: 'Surface Klaviyo flows with drops in open rates and prompt you to review the messaging before revenue is lost.',
    domain: 'klaviyo.com',
  },

  // ── Messaging & Meetings ──

  {
    id: 'slack',
    name: 'Slack',
    category: 'Messaging & Meetings',
    status: 'early_access',
    whatItDoes: 'Spot client messages buried in busy Slack channels and surface action items before they slip through.',
    domain: 'slack.com',
  },
  {
    id: 'whatsapp-business',
    name: 'WhatsApp Business',
    category: 'Messaging & Meetings',
    status: 'coming_soon',
    whatItDoes: 'Flag unanswered WhatsApp Business messages from clients and draft a reply before the conversation goes cold.',
    domain: 'business.whatsapp.com',
  },
  {
    id: 'telegram',
    name: 'Telegram',
    category: 'Messaging & Meetings',
    status: 'coming_soon',
    whatItDoes: 'Surface unanswered Telegram messages from clients and collaborators and prompt you to reply.',
    domain: 'telegram.org',
  },
  {
    id: 'sms-twilio',
    name: 'SMS via Twilio',
    category: 'Messaging & Meetings',
    status: 'coming_soon',
    whatItDoes: 'Flag unanswered client SMS messages and draft a brief reply so no text goes unacknowledged.',
    domain: 'twilio.com',
  },
  {
    id: 'zoom',
    name: 'Zoom',
    category: 'Messaging & Meetings',
    status: 'coming_soon',
    whatItDoes: 'Detect upcoming Zoom calls without a confirmed agenda and prompt you to send a prep note to the client.',
    domain: 'zoom.us',
  },
  {
    id: 'google-meet',
    name: 'Google Meet',
    category: 'Messaging & Meetings',
    status: 'coming_soon',
    whatItDoes: 'Flag scheduled Google Meet calls with no pre-call brief and draft a short agenda to share with the client.',
    domain: 'meet.google.com',
  },
  {
    id: 'microsoft-teams',
    name: 'Microsoft Teams',
    category: 'Messaging & Meetings',
    status: 'coming_soon',
    whatItDoes: 'Surface unread Teams messages from clients and prompt you to reply before the conversation grows stale.',
    domain: 'microsoft.com',
  },

  // ── E-commerce & Sites ──

  {
    id: 'shopify',
    name: 'Shopify',
    category: 'E-commerce & Sites',
    status: 'coming_soon',
    whatItDoes: 'Flag open Shopify customer support conversations and low-stock products before they cost you sales.',
    domain: 'shopify.com',
  },
  {
    id: 'etsy',
    name: 'Etsy',
    category: 'E-commerce & Sites',
    status: 'coming_soon',
    whatItDoes: 'Surface unanswered Etsy customer messages and flag negative reviews that need a timely response.',
    domain: 'etsy.com',
  },
  {
    id: 'squarespace',
    name: 'Squarespace',
    category: 'E-commerce & Sites',
    status: 'coming_soon',
    whatItDoes: 'Detect Squarespace contact form submissions that have not received a reply and draft an introductory message.',
    domain: 'squarespace.com',
  },
  {
    id: 'wix',
    name: 'Wix',
    category: 'E-commerce & Sites',
    status: 'coming_soon',
    whatItDoes: 'Surface Wix Inbox messages from site visitors and draft replies to convert enquiries into bookings.',
    domain: 'wix.com',
  },
  {
    id: 'woocommerce',
    name: 'WooCommerce',
    category: 'E-commerce & Sites',
    status: 'coming_soon',
    whatItDoes: 'Flag unresponded WooCommerce customer queries and orders stuck in a pending state before they escalate.',
    domain: 'woocommerce.com',
  },

  // ── Project & Productivity ──

  {
    id: 'asana',
    name: 'Asana',
    category: 'Project & Productivity',
    status: 'coming_soon',
    whatItDoes: 'Surface Asana tasks approaching their due date with no recent activity and nudge the right person to act.',
    domain: 'asana.com',
  },
  {
    id: 'trello',
    name: 'Trello',
    category: 'Project & Productivity',
    status: 'coming_soon',
    whatItDoes: 'Flag Trello cards that have sat in the same column for too long and prompt you to move them forward.',
    domain: 'trello.com',
  },
  {
    id: 'clickup',
    name: 'ClickUp',
    category: 'Project & Productivity',
    status: 'coming_soon',
    whatItDoes: 'Surface overdue ClickUp tasks and prompt you to update the status or reassign before the deadline passes.',
    domain: 'clickup.com',
  },
  {
    id: 'monday-com',
    name: 'Monday.com',
    category: 'Project & Productivity',
    status: 'coming_soon',
    whatItDoes: 'Flag Monday boards with items stuck at the same status for too long and draft a stakeholder update.',
    domain: 'monday.com',
  },
  {
    id: 'todoist',
    name: 'Todoist',
    category: 'Project & Productivity',
    status: 'coming_soon',
    whatItDoes: 'Surface overdue Todoist tasks labelled as client deliverables and prompt you to reschedule or complete them.',
    domain: 'todoist.com',
  },
  {
    id: 'basecamp',
    name: 'Basecamp',
    category: 'Project & Productivity',
    status: 'coming_soon',
    whatItDoes: 'Flag Basecamp to-dos with past due dates and unanswered message board posts before clients follow up themselves.',
    domain: 'basecamp.com',
  },
  {
    id: 'things',
    name: 'Things',
    category: 'Project & Productivity',
    status: 'coming_soon',
    whatItDoes: 'Surface Things tasks tagged as client work that are overdue and remind you to act on them today.',
    domain: 'culturedcode.com',
  },
  {
    id: 'ticktick',
    name: 'TickTick',
    category: 'Project & Productivity',
    status: 'coming_soon',
    whatItDoes: 'Flag TickTick tasks with missed due dates and prompt you to reschedule or hand them off.',
    domain: 'ticktick.com',
  },
  {
    id: 'microsoft-todo',
    name: 'Microsoft To Do',
    category: 'Project & Productivity',
    status: 'coming_soon',
    whatItDoes: 'Surface overdue Microsoft To Do items flagged as important and prompt you to complete or reschedule them.',
    domain: 'todo.microsoft.com',
  },
  {
    id: 'motion',
    name: 'Motion',
    category: 'Project & Productivity',
    status: 'coming_soon',
    whatItDoes: 'Alert you when Motion has rescheduled a task multiple times and prompt you to decide whether to delegate or drop it.',
    domain: 'usemotion.com',
  },
  {
    id: 'wrike',
    name: 'Wrike',
    category: 'Project & Productivity',
    status: 'coming_soon',
    whatItDoes: 'Flag Wrike project tasks overdue or blocked and draft a status update for the client or project owner.',
    domain: 'wrike.com',
  },
  {
    id: 'sunsama',
    name: 'Sunsama',
    category: 'Project & Productivity',
    status: 'coming_soon',
    whatItDoes: 'Flag client-linked tasks left incomplete at end of day in Sunsama and prompt you to carry them forward with context.',
    domain: 'sunsama.com',
  },

  // ── Time Tracking ──

  {
    id: 'toggl-track',
    name: 'Toggl Track',
    category: 'Time Tracking',
    status: 'coming_soon',
    whatItDoes: 'Detect unbilled Toggl time entries for client projects and prompt you to add them to the next invoice.',
    domain: 'toggl.com',
  },
  {
    id: 'harvest',
    name: 'Harvest',
    category: 'Time Tracking',
    status: 'coming_soon',
    whatItDoes: 'Flag Harvest time entries that have not been invoiced and prompt you to bill the client before hours accumulate.',
    domain: 'getharvest.com',
  },
  {
    id: 'clockify',
    name: 'Clockify',
    category: 'Time Tracking',
    status: 'coming_soon',
    whatItDoes: 'Surface unbilled Clockify hours for each client and prompt you to turn them into an invoice.',
    domain: 'clockify.me',
  },
  {
    id: 'rescuetime',
    name: 'RescueTime',
    category: 'Time Tracking',
    status: 'coming_soon',
    whatItDoes: 'Flag weeks where focus time dipped significantly and prompt you to review what pulled your attention away.',
    domain: 'rescuetime.com',
  },

  // ── Developer & Technical ──

  {
    id: 'github',
    name: 'GitHub',
    category: 'Developer & Technical',
    status: 'coming_soon',
    whatItDoes: 'Surface pull requests awaiting your review and issues overdue for a response before clients grow frustrated.',
    domain: 'github.com',
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    category: 'Developer & Technical',
    status: 'coming_soon',
    whatItDoes: 'Flag GitLab merge requests that have stalled in review and prompt you to move them to completion.',
    domain: 'gitlab.com',
  },
  {
    id: 'bitbucket',
    name: 'Bitbucket',
    category: 'Developer & Technical',
    status: 'coming_soon',
    whatItDoes: 'Surface Bitbucket pull requests awaiting approval and flag repos with unresolved comments.',
    domain: 'bitbucket.org',
  },
  {
    id: 'linear',
    name: 'Linear',
    category: 'Developer & Technical',
    status: 'coming_soon',
    whatItDoes: 'Detect Linear issues assigned to you that are past their target date and prompt you to update the cycle.',
    domain: 'linear.app',
  },
  {
    id: 'jira',
    name: 'Jira',
    category: 'Developer & Technical',
    status: 'coming_soon',
    whatItDoes: 'Flag Jira tickets in your backlog overdue for a sprint update and draft a status comment for the client.',
    domain: 'atlassian.com',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    category: 'Developer & Technical',
    status: 'coming_soon',
    whatItDoes: 'Alert you when a Vercel deployment fails and draft a brief status update to send the client while you investigate.',
    domain: 'vercel.com',
  },
  {
    id: 'netlify',
    name: 'Netlify',
    category: 'Developer & Technical',
    status: 'coming_soon',
    whatItDoes: 'Flag failed Netlify builds or form submissions that have gone unread and prompt you to act.',
    domain: 'netlify.com',
  },

  // ── Freelance Marketplaces ──

  {
    id: 'upwork',
    name: 'Upwork',
    category: 'Freelance Marketplaces',
    status: 'coming_soon',
    whatItDoes: 'Surface unanswered Upwork client messages and contract milestones due for approval before they escalate.',
    domain: 'upwork.com',
  },
  {
    id: 'fiverr',
    name: 'Fiverr',
    category: 'Freelance Marketplaces',
    status: 'coming_soon',
    whatItDoes: 'Flag Fiverr orders approaching their delivery deadline and draft a status update to keep the buyer informed.',
    domain: 'fiverr.com',
  },
  {
    id: 'contra',
    name: 'Contra',
    category: 'Freelance Marketplaces',
    status: 'coming_soon',
    whatItDoes: 'Surface Contra project enquiries and proposal requests before the response window closes.',
    domain: 'contra.com',
  },
  {
    id: 'freelancer-com',
    name: 'Freelancer.com',
    category: 'Freelance Marketplaces',
    status: 'coming_soon',
    whatItDoes: 'Detect unanswered Freelancer.com messages from contest holders and draft a timely reply.',
    domain: 'freelancer.com',
  },

  // ── Print & Fulfillment ──

  {
    id: 'printful',
    name: 'Printful',
    category: 'Print & Fulfillment',
    status: 'coming_soon',
    whatItDoes: 'Flag Printful orders held for your approval or stuck in production and prompt you to resolve them before the customer complains.',
    domain: 'printful.com',
  },
  {
    id: 'printify',
    name: 'Printify',
    category: 'Print & Fulfillment',
    status: 'coming_soon',
    whatItDoes: 'Surface Printify orders with a delayed fulfilment status and prompt you to contact the print provider.',
    domain: 'printify.com',
  },
  {
    id: 'big-cartel',
    name: 'Big Cartel',
    category: 'Print & Fulfillment',
    status: 'coming_soon',
    whatItDoes: 'Flag new Big Cartel orders that have not been marked as shipped after 48 hours and draft an update to the buyer.',
    domain: 'bigcartel.com',
  },
  {
    id: 'redbubble',
    name: 'Redbubble',
    category: 'Print & Fulfillment',
    status: 'coming_soon',
    whatItDoes: 'Surface new Redbubble fan messages and flag product listings flagged for a policy issue before sales stall.',
    domain: 'redbubble.com',
  },

  // ── Automation ──

  {
    id: 'zapier',
    name: 'Zapier',
    category: 'Automation',
    status: 'coming_soon',
    whatItDoes: 'Bridge your nibbins to hundreds of other tools via Zapier so actions you approve can trigger downstream workflows automatically.',
    domain: 'zapier.com',
  },
  {
    id: 'make',
    name: 'Make',
    category: 'Automation',
    status: 'coming_soon',
    whatItDoes: 'Connect your nibbins to Make scenarios to fan approved actions out across hundreds of apps in one step.',
    domain: 'make.com',
  },
  {
    id: 'n8n',
    name: 'n8n',
    category: 'Automation',
    status: 'coming_soon',
    whatItDoes: 'Bridge nibbin-approved actions to n8n workflows that can reach hundreds of self-hosted or cloud tools.',
    domain: 'n8n.io',
  },
  {
    id: 'ifttt',
    name: 'IFTTT',
    category: 'Automation',
    status: 'coming_soon',
    whatItDoes: 'Route nibbin-approved triggers through IFTTT to hundreds of consumer apps and smart-home services.',
    domain: 'ifttt.com',
  },
  {
    id: 'pipedream',
    name: 'Pipedream',
    category: 'Automation',
    status: 'coming_soon',
    whatItDoes: 'Forward nibbin-approved events to Pipedream workflows that connect to hundreds of APIs and data sources.',
    domain: 'pipedream.com',
  },

  // ── Advanced ──

  {
    id: 'generic-mcp',
    name: 'Custom MCP Server',
    category: 'Advanced',
    status: 'early_access',
    whatItDoes: 'Connect any tool that exposes an MCP interface so your nibbins can watch it and propose actions.',
    domain: null,
  },
  {
    id: 'webhook-rail',
    name: 'Webhooks',
    category: 'Advanced',
    status: 'early_access',
    whatItDoes: 'Receive events from any webhook-enabled tool and route them into nibbin workflows for review and approval.',
    domain: null,
  },
  {
    id: 'csv-import',
    name: 'CSV Import',
    category: 'Advanced',
    status: 'early_access',
    whatItDoes: 'Upload a CSV of contacts, invoices, or tasks and let your nibbins spot the gaps and draft the first actions.',
    domain: null,
  },
];
